import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,available,budget,timeBudget,forecast,selectCards,resolveYear,chooseEvent,chooseRelic,validateSave,move,reroll,ending} from '../dist/engine.js';
import {EVENTS} from '../dist/data.js';
function best(s){const hand=available(s),options=[];for(let mask=1;mask<32;mask++){const cards=hand.filter((_,i)=>mask&(1<<i));if(cards.length>3)continue;const ids=cards.map(c=>c.id),b=budget(s,ids);if(b.time>timeBudget(s)||b.cost>b.available)continue;const f=forecast(s,ids),score=Object.entries(f.deltas).reduce((sum,[k,v])=>sum+v*(100-s.stats[k])/70,0)-Math.max(0,s.load+f.load-40)*.3;options.push({ids,score});}return options.sort((a,b)=>b.score-a.score)[0].ids;}
function play(seed){let s=newGame({seed});while(s.phase!=='end'){if(s.phase==='plan')s=resolveYear(selectCards(s,best(s)));else if(s.phase==='event'){const e=EVENTS.find(e=>e.id===s.eventId);s=chooseEvent(s,e.choices.findIndex(c=>c.cost<=s.cash));}else s=chooseRelic(s,s.draft[0]);assert.doesNotThrow(()=>validateSave(JSON.parse(JSON.stringify(s))));assert.ok(s.cash>=0);for(const v of Object.values(s.stats))assert.ok(v>=0&&v<=100);}return s;}
test('100 seeded games complete, stay bounded, and round-trip saves at every phase',()=>{for(let i=0;i<100;i++){const s=play('QA-'+i);assert.equal(s.age,18);assert.equal(s.history.length,18);assert.equal(s.relics.length,5);assert.ok(ending(s).name);}});
test('same seed plus same decisions produces the same complete life',()=>assert.deepEqual(play('REPEAT'),play('REPEAT')));
test('rejects unavailable, duplicate, oversized plans and out-of-order actions without mutation',()=>{const s=newGame(),snapshot=JSON.stringify(s),id=available(s)[0].id;assert.throws(()=>selectCards(s,[id,id]));assert.throws(()=>selectCards(s,['nonexistent']));assert.throws(()=>selectCards(s,available(s).map(c=>c.id)));assert.throws(()=>chooseEvent(s,0));assert.throws(()=>chooseRelic(s,'pages'));assert.throws(()=>resolveYear(s));assert.equal(JSON.stringify(s),snapshot);});
test('a depleted budget never traps a player at an event',()=>{assert.ok(EVENTS.every(e=>e.choices.some(c=>c.cost===0)));for(const e of EVENTS){const s={...newGame(),phase:'event',eventId:e.id,cash:0,last:{}};assert.doesNotThrow(()=>chooseEvent(s,e.choices.findIndex(c=>c.cost===0)));}});
test('moving and changing cards costs funds and cannot be repeated within a year',()=>{let s=move(newGame(),'library');assert.equal(s.cash,15);assert.throws(()=>move(s,'garden'));s=reroll(s);assert.equal(s.cash,14);assert.throws(()=>reroll(s));});
test('corrupt saves rejected and forecast matches pre-event execution',()=>{const s=newGame(),p=selectCards(s,best(s)),f=forecast(p),r=resolveYear(p);for(const k of Object.keys(s.stats))assert.equal(r.stats[k]-s.stats[k],f.deltas[k]);assert.throws(()=>validateSave({...s,age:18}));assert.throws(()=>validateSave({...s,cash:NaN}));assert.throws(()=>validateSave({...s,relics:['fake']}));assert.throws(()=>validateSave({...r,last:{}}));});
