import { createFileRoute } from "@tanstack/react-router";
import { Chrome } from "@/components/atlas/Chrome";
import { useAtlas } from "@/lib/atlas/store";
export const Route = createFileRoute("/methodology")({ component: MethodologyPage });
function MethodologyPage() {
  const zh = useAtlas((s) => s.lang) === "zh";
  return <Chrome><article className="mx-auto h-full max-w-3xl overflow-y-auto px-5 py-8 text-base leading-relaxed text-paper-2">
    <h1 className="mb-3 text-3xl font-semibold text-paper">{zh ? "先看懂，再当真。" : "Read this before the numbers."}</h1>
    <p className="mb-8 text-xl">{zh ? "地图不是算命。算命一般不公开代码。" : "A model, not a crystal ball. This one shares its code."}</p>
    <div className="space-y-8">
      <section><h2 className="mb-2 text-xl text-paper">{zh ? "怎么用" : "How to use it"}</h2><p>{zh ? "选城市，拖动父母收入的位置，点一个区。再去「比一比」选两个区，看同样的家庭起点，在模型里有什么差别。" : "Choose a city, move the parent-income slider, and pick a district. Compare two districts using the same family starting point."}</p></section>
      <section><h2 className="mb-2 text-xl text-paper">{zh ? "数字从哪来" : "Where the numbers come from"}</h2><p>{zh ? "北京、上海、广州、深圳、成都、杭州拆到街道或镇。轮廓是 OSM 裁进既有区界，不是民政原件。除南山 8 个街道外，收入和学校等指标沿用所在区，所以同一个区里颜色一样；人口按区常住人口做面积分摊，不是街道公报。南山仍是区级数字按可核对功能做的平移。成都青白江、大邑、彭州、邛崃、简阳盖不住，仍是整区。杭州收入是 2023 年市统计局 1–12 月全体居民人均可支配收入，人口是 2023 年末常住人口公报。香港收入仍是 2021 年普查。" : "Beijing, Shanghai, Guangzhou, Shenzhen, Chengdu and Hangzhou are split to streets or towns. Outlines are OSM clipped into the existing district polygon, not civil-affairs originals. Except eight Nanshan streets, income and covariates are the parent district figures, so streets in one district share a color. Population is an area share, not a street bulletin. Five Chengdu units stayed whole because OSM did not cover them. Hangzhou income is the 2023 statistical bureau Jan–Dec figure; population is year-end 2023. Hong Kong income remains the 2021 census."}</p><p className="mt-3">{zh ? "屏幕上的成年收入、上大学和有房概率，都是公式算出的模拟值。这个项目没有用真实孩子长大后的结果验证这些预测。" : "Adult income, college and homeownership outcomes are calculated simulations. These predictions have not been validated against observed adult outcomes for children."}</p></section>
      <section><h2 className="mb-2 text-xl text-paper">{zh ? "颜色怎么读" : "Reading the colors"}</h2><p>{zh ? "颜色表示当前假设下的模型结果高低。看收入时，地图颜色按模拟收入位置上色，数字显示家庭年收入。内地用人民币，香港用港元，不能直接把两个金额相减。" : "Colors show lower or higher model outputs under the selected assumptions. For income, color uses simulated income rank while amounts show annual household income. Mainland amounts are CNY; Hong Kong amounts are HKD, so they cannot be directly subtracted."}</p></section>
      <section><h2 className="mb-2 text-xl text-paper">{zh ? "哪些事，它不知道" : "What it cannot tell you"}</h2><ul className="list-disc space-y-2 pl-5">
        <li>{zh ? "你或孩子将来挣多少。人生没有在这张表里报备。" : "What you or your child will actually earn."}</li>
        <li>{zh ? "搬家会不会让人更有钱。搬家模块只是按居住年数折算，没有真实搬迁实验。" : "Whether moving causes higher income. The moving module is a years-of-exposure assumption, not an experiment."}</li>
        <li>{zh ? "具体小区或学校怎么样。一个区太大，平均数会把很多差别藏起来。" : "What an individual school or neighborhood is like. District averages hide local variation."}</li>
        <li>{zh ? "哪个地方最适合买房或养娃。评分权重、性别调整和城市参数都是模型设定。" : "Where you should buy a home or raise a child. Weights, gender adjustments and city parameters are assumptions."}</li>
      </ul></section>
      <details className="rounded-md border border-line p-4"><summary className="cursor-pointer text-paper">{zh ? "想看公式？展开。" : "Want the formula?"}</summary><div className="mt-4 space-y-3"><p>{zh ? "先把七项环境评分加权，再加上家庭起点和性别的假设影响。公式与原版一致；这些系数不是本项目从区级孩子收入数据中估计出来的。" : "Seven context scores are weighted, then combined with assumed family and gender terms. The original formulas are unchanged; their coefficients are not fitted to observed district-level child outcomes in this project."}</p><pre className="overflow-x-auto text-sm">{`Q = (0.28 school + 0.16 university + 0.16 inverse-poverty\n   + 0.12 income-mix + 0.12 skilled-jobs\n   + 0.08 school-access + 0.08 transport) / 100\n\nR = clamp(50 + ρ × (p − 50) + θ × (Q − 0.5) × 100 + γ, 3, 97)\nθ = 0.22 + 0.28 × (1 − p/100)`}</pre><p>{zh ? "p 是父母的收入位置，Q 是环境评分，R 是模拟收入位置。随后用城市参数换算金额。更复杂，不等于更准确。" : "p is parent rank, Q is context score and R is simulated child rank. City parameters convert rank into income. More complicated does not mean more accurate."}</p></div></details>
      <section><h2 className="mb-2 text-xl text-paper">{zh ? "一起把它做得更靠谱" : "Help improve it"}</h2><p>{zh ? "发现错误、拿到更好的数据，欢迎来改。先把不知道的地方写清楚，再一点点知道更多。" : "Found an error or better data? Contributions are welcome. Start by making the unknowns visible."}</p><div className="mt-4 flex flex-wrap gap-5 text-accent"><a href="https://github.com/Ericnotme/opportunity-atlas-china/tree/main/plain" target="_blank" rel="noreferrer">GitHub</a><a href={`${import.meta.env.BASE_URL}data/districts.csv`} download>{zh ? "下载原始输入表" : "Download inputs"}</a><a href="https://www.opportunityatlas.org/" target="_blank" rel="noreferrer">{zh ? "灵感来源：美国 Opportunity Atlas" : "Inspiration: US Opportunity Atlas"}</a></div></section>
    </div>
  </article></Chrome>;
}
